### **Лабораторная работа 3**

***
__ПОСИИ__
***

In [56]:
# Импортование необходимых модулей
import numpy as np
import tensorflow as tf
mnist = tf.keras.datasets.mnist
to_categorical = tf.keras.utils.to_categorical
Sequential = tf.keras.models.Sequential
Dense = tf.keras.layers.Dense

# Загрузка данных
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Преобразование данных
x_train = x_train.reshape(x_train.shape[0], -1) / 255.0
x_test = x_test.reshape(x_test.shape[0], -1) / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [58]:
# Архитектура сети 1:
model = Sequential()
model.add(Dense(10, input_dim=784, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])

# Обучение:
model.fit(x_train, y_train, epochs=10, validation_split=0.1)

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 974us/step - accuracy: 0.7549 - loss: 0.8422 - val_accuracy: 0.9228 - val_loss: 0.2753
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 928us/step - accuracy: 0.9088 - loss: 0.3192 - val_accuracy: 0.9278 - val_loss: 0.2504
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 927us/step - accuracy: 0.9176 - loss: 0.2873 - val_accuracy: 0.9340 - val_loss: 0.2347
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 922us/step - accuracy: 0.9218 - loss: 0.2745 - val_accuracy: 0.9365 - val_loss: 0.2280
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 991us/step - accuracy: 0.9239 - loss: 0.2720 - val_accuracy: 0.9382 - val_loss: 0.2231
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9278 - loss: 0.2614 - val_accuracy: 0.9367 - val_loss: 0.2267
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9293 - loss: 0.2535 - val_accuracy: 0.9387 - val_loss: 0.2222
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9293 - loss:

In [59]:
# Анализ результата 1 на проверочных и тестовых данных.
test_acc = model.evaluate(x_test, y_test)
print(test_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.9163 - loss: 0.2945
[0.2629081904888153, 0.9248999953269958]


In [ ]:
# Архитектура сети 2:
model2 = Sequential()
model2.add(Dense( 50, input_dim=784, activation='relu'))
model2.add(Dense(10, activation='softmax'))
model2.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])
model2.fit(x_train, y_train, epochs=10, validation_split=0.1)

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8427 - loss: 0.5664 - val_accuracy: 0.9550 - val_loss: 0.1677
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9460 - loss: 0.1867 - val_accuracy: 0.9632 - val_loss: 0.1292
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9619 - loss: 0.1303 - val_accuracy: 0.9670 - val_loss: 0.1089
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9719 - loss: 0.0982 - val_accuracy: 0.9707 - val_loss: 0.0995
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9755 - loss: 0.0823 - val_accuracy: 0.9710 - val_loss: 0.1011
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9790 - loss: 0.0706 - val_accuracy: 0.9728 - val_loss: 0.0913
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9809 - loss: 0.0609 - val_accuracy: 0.9755 - val_loss: 0.0933
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9833 - loss: 0.0550 - 

In [ ]:
# Анализ результата 2 на проверочных и тестовых данных.
test_acc = model2.evaluate(x_test, y_test)
print(test_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.9692 - loss: 0.1182
[0.09958184510469437, 0.9733999967575073]


In [ ]:
# Архитектура сети 3:
model3 = Sequential()
model3.add(Dense(50, input_dim=784, activation='relu'))
model3.add(Dense(50, activation='relu'))
model3.add(Dense(10, activation='softmax'))
model3.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])
model3.fit(x_train, y_train, epochs=10, validation_split=0.1)

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8397 - loss: 0.5519 - val_accuracy: 0.9600 - val_loss: 0.1372
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9546 - loss: 0.1542 - val_accuracy: 0.9680 - val_loss: 0.1098
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9667 - loss: 0.1084 - val_accuracy: 0.9677 - val_loss: 0.1067
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9751 - loss: 0.0836 - val_accuracy: 0.9738 - val_loss: 0.0916
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9789 - loss: 0.0662 - val_accuracy: 0.9747 - val_loss: 0.0917
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9821 - loss: 0.0577 - val_accuracy: 0.9748 - val_loss: 0.0980
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9852 - loss: 0.0476 - val_accuracy: 0.9755 - val_loss: 0.0875
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9871 - loss: 0.0407 - 

In [ ]:
# Анализ результата 3 на проверочных и тестовых данных.
test_acc = model3.evaluate(x_test, y_test)
print(test_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.9606 - loss: 0.1456
[0.12438387423753738, 0.9664000272750854]


In [ ]:
# Импортование необходимых модулей
Conv2D = tf.keras.layers.Conv2D
MaxPooling2D = tf.keras.layers.MaxPooling2D
Flatten = tf.keras.layers.Flatten

In [ ]:
fashion_mnist = tf.keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train[:,:,:,np.newaxis] / 255.0
x_test = x_test[:,:,:,np.newaxis] / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [ ]:
# Архитектура сети 4:
model4 = Sequential()
model4.add(Conv2D(filters=64, kernel_size=2, padding='same',
activation='relu', input_shape=(28,28, 1)))
model4.add(MaxPooling2D(pool_size=2))
model4.add(Flatten())
model4.add(Dense(10, activation='softmax'))
model4.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])
model4.fit(x_train, y_train, epochs=10, validation_split=0.1)

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.8023 - loss: 0.5763 - val_accuracy: 0.8818 - val_loss: 0.3288
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8891 - loss: 0.3165 - val_accuracy: 0.8957 - val_loss: 0.3050
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9019 - loss: 0.2789 - val_accuracy: 0.8868 - val_loss: 0.3094
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9078 - loss: 0.2593 - val_accuracy: 0.8987 - val_loss: 0.2839
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9134 - loss: 0.2404 - val_accuracy: 0.9032 - val_loss: 0.2678
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9219 - loss: 0.2192 - val_accuracy: 0.8950 - val_loss: 0.3018
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9241 - loss: 0.2166 - val_accuracy: 0.9047 - val_loss: 0.2719
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9299 - loss: 0

In [ ]:
# Анализ результата 4 на проверочных и тестовых данных.
test_acc = model4.evaluate(x_test, y_test)
print(test_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9021 - loss: 0.2795
[0.27876409888267517, 0.9009000062942505]


***
##### **Проведите сравнение работы четырех архитектур. Какая из архитектур показывает лучший результат и почему? Как можно улучшить результаты каждой из архитектур?**

###### Архитектура 1: Простая полносвязная сеть
- Структура: 1 скрытый слой с 10 нейронами.
- Результаты: Ожидается, что эта архитектура покажет низкую точность, так как она слишком проста для решения задачи классификации изображений.

###### Архитектура 2: Увеличенный скрытый слой
- Структура: 1 скрытый слой с 50 нейронами.
- Результаты: Эта архитектура должна показать улучшение по сравнению с первой, так как большее количество нейронов позволяет лучше захватывать паттерны в данных.

###### Архитектура 3: Глубокая полносвязная сеть
- Структура: 2 скрытых слоя, каждый с 50 нейронами.
- Результаты: Ожидается, что эта архитектура будет иметь наилучшие результаты среди полносвязных сетей, так как она может моделировать более сложные функции.

###### Архитектура 4: Сверточная нейронная сеть (CNN)
- Структура: Сверточный слой, слой подвыборки и полносвязный слой.
- Результаты: CNN обычно показывает наилучшие результаты для задач классификации изображений, так как они могут эффективно извлекать пространственные и временные зависимости из изображений.

***
##### Сравнение результатов
Наилучшие результаты: архитектура 4 (CNN) показывает наилучшие результаты по сравнению с другими архитектурами, так как она специально разработана для обработки изображений и может извлекать более сложные признаки.
***

##### Улучшение других архитектур:
- Архитектура 1 и 2: Можно увеличить количество нейронов в скрытых слоях и добавить регуляризацию (например, Dropout), чтобы избежать переобучения.
- Архитектура 3: Можно попробовать увеличить количество слоев или нейронов, а также использовать различные функции активации (например, Leaky ReLU).
- Архитектура 4: Можно добавить больше сверточных слоев, использовать различные размеры ядер свертки и увеличить количество фильтров для улучшения извлечения признаков.
***

По вариантам (в соответствии с номером в списке) спроектируйте архитектуру, реализуйте алгоритм корректировки синаптических весов с помощью алгоритма обратного распространения ошибки, используя в качестве функции активации логистический сигмоид 𝑓(𝑛𝑒𝑡) = 1/(1+exp(-net))

**Вариант 4**
- Архитектура: 3-4-3
- Скорость обучения: 0.4
- Входной вектор: X={0.4; -0.7; 1.3}
- Матрицы синапсов 1 и 2 слоя: Начальные значения весов взять произвольным образом из интервала [-0.3 0.3]
- Эталонный выход: Y = {0.3; -0.5; 0.8}

In [67]:
import numpy as np
import tensorflow as tf
Sequential = tf.keras.models.Sequential
Dense = tf.keras.layers.Dense

# Установка скорости обучения
learning_rate = 0.3

# Входной вектор
input_vector = np.array([0.4, -0.7, 1.3])

# Эталонный выход
target_output = np.array([0.3, -0.5, 0.8])

# Инициализация весов случайными значениями из интервала [-0.3, 0.3]
weights_input_hidden = np.random.uniform(-0.3, 0.3, (3, 4))   # Веса между входным и скрытым слоями
weights_hidden_output = np.random.uniform(-0.3, 0.3, (4, 3))  # Веса между скрытым и выходным слоями

# Функция активации: логистическая сигмоида
def sigmoid(x):
    """
    Функция активации: логистическая сигмоида.
    
    Параметры:
    x (numpy.ndarray): Входные данные для функции активации.
    
    Возвращает:
    numpy.ndarray: Выходные данные после применения сигмоиды.
    """
    return 1 / (1 + np.exp(-x))

# Производная функции активации
def sigmoid_derivative(x):
    """
    Производная функции активации сигмоиды.
    
    Параметры:
    x (numpy.ndarray): Выходные данные функции активации.
    
    Возвращает:
    numpy.ndarray: Производная функции активации.
    """
    return x * (1 - x)

# Обучение сети
for epoch in range(25):  # Количество эпох
    # Прямое распространение
    hidden_layer_input = np.dot(input_vector, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output_layer_output = sigmoid(output_layer_input)

    # Ошибка
    error = target_output - output_layer_output

    # Обратное распространение
    d_predicted_output = error * output_layer_output * (1 - output_layer_output)
    error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * hidden_layer_output * (
        1 - hidden_layer_output)

    # Обновление весов
    weights_hidden_output += hidden_layer_output.reshape(-1, 1).dot(
        d_predicted_output.reshape(1, -1)) * learning_rate
    weights_input_hidden += input_vector.reshape(-1, 1).dot(
        d_hidden_layer.reshape(1, -1)) * learning_rate

# Результаты после обучения
print("Обученные веса между входным и скрытым слоями:")
print(weights_input_hidden)
print("Обученные веса между скрытым и выходным слоями:")
print(weights_hidden_output)

# Проверка предсказания
print("Предсказанный выход после обучения:")
print(output_layer_output)

Обученные веса между входным и скрытым слоями:
[[ 0.18684483  0.26355246 -0.12372625 -0.15696435]
 [ 0.07021499  0.04153902  0.28196033 -0.11643026]
 [ 0.07206802  0.43060545 -0.07259561  0.37731315]]
Обученные веса между скрытым и выходным слоями:
[[ 0.01168556 -0.64172869  0.3624883 ]
 [-0.09305864 -0.96050232  0.49752545]
 [-0.16492517 -0.30156217  0.06746499]
 [-0.00866185 -0.79258816 -0.03695764]]
Предсказанный выход после обучения:
[0.47208287 0.17617597 0.62324994]


***
#### Контрольные вопросы:
**1. Понятие нейронной сети, архитектуры**

Нейронная сеть — это вычислительная модель, вдохновленная структурой и функциями биологических нейронных сетей. Она состоит из узлов (нейронов), которые связаны между собой и могут обрабатывать информацию.

Архитектура нейронной сети определяется количеством слоев (входной, скрытые и выходной) и количеством нейронов в каждом слое.

**2. Обучение нейронной сети**

Обучение нейронной сети — это процесс, в ходе которого сеть настраивает свои параметры (веса) на основе обучающей выборки. Это позволяет сети минимизировать ошибку предсказания и улучшать свою производительность на новых данных.

**3. Основные определения: скорость обучения, эпоха, нейрон, обучающая выборка, тестовая выборка, вариационная выборка, функция активации.**

- Скорость обучения — это параметр, который определяет, насколько сильно обновляются веса нейронной сети на каждом шаге обучения. Высокая скорость может привести к нестабильности, а низкая — к медленному обучению.
- Эпоха — это один полный проход через всю обучающую выборку. Обычно обучение включает множество эпох.
- Нейрон — это базовый элемент нейронной сети, который принимает входные данные, применяет к ним веса и функцию активации, чтобы выдать выходное значение.
- Обучающая выборка — это набор данных, используемый для обучения модели.
- Тестовая выборка — это набор данных, используемый для оценки производительности модели после обучения.
- Вариационная выборка — это набор данных, который может использоваться для настройки гиперпараметров модели.
- Функция активации — это функция, которая определяет выход нейрона на основе его входных данных. Она помогает сети обучаться сложным зависимостям.

**4. Алгоритм обратного распространения ошибки**

Алгоритм обратного распространения ошибки (backpropagation) — это метод, используемый для обучения нейронных сетей. Он включает в себя два этапа: прямое распространение, где входные данные проходят через сеть и генерируют выход, и обратное распространение, где вычисляется градиент ошибки и обновляются веса сети. Этот процесс повторяется до тех пор, пока ошибка не станет приемлемой.

**5. Типы функций активации**

Существует несколько типов функций активации, включая:
- Сигмоидная функция — преобразует входные данные в диапазон от 0 до 1.
- Гиперболический тангенс — преобразует входные данные в диапазон от -1 до 1.
- ReLU (Rectified Linear Unit) — возвращает 0 для отрицательных входов и сам вход для положительных, что помогает избежать проблемы затухающего градиента.

**6. Алгоритмы обучения**

Существует несколько алгоритмов обучения нейронных сетей, включая:
- Градиентный спуск — основной метод, который минимизирует функцию потерь, обновляя веса в направлении отрицательного градиента.
- Стохастический градиентный спуск (SGD) — вариант градиентного спуска, который обновляет веса на основе одного примера из обучающей выборки.
- Адаптивные методы (например, Adam, RMSprop) — алгоритмы, которые адаптируют скорость обучения для каждого веса на основе их градиентов.